# Generated by Django 2.0.1 on 2018-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20180507_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(default='/default/post-header.png', upload_to='user-header-images'),
        ),
    ]
