# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# services:
#   - mysql:latest
#   - postgres:latest
# variables:
#   POSTGRES_DB: database_name

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/

stages:
  - pullUpdates
  - updateStaticAndReloadApp


djangoAppUpdate:
  stage: pullUpdates
  tags:
    - mheans
  script:
    - cd /home/oluwanifemi/AskolonyAPI
    - git pull origin withFeeds
  only:
    - withFeeds
    

updateAndReloadDjangoApp:
  stage: updateStaticAndReloadApp
  tags:
    - mheans
  script:
#    - source /home/senso/django_env/bin/activate
#    - python -V
#    - yes | python /home/senso/trade-fufilment/manage.py collectstatic
    - pkill gunicorn                      # Print out python version for debugging
    - pkill celery
    - sudo chmod u+x /home/oluwanifemi/AskolonyAPI/gunicorn_start.bash
    - sudo service supervisor restart
  only:
    - mheans
    

# test:
#   variables:
#     DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
#   script:
#   - python manage.py test
