# Generated by Django 2.0.1 on 2018-03-15 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0002_auto_20180307_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUpvotes',
            new_name='PostUpvote',
        ),
    ]
