# Generated by Django 2.0.1 on 2018-03-22 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0005_flaggedcomment_flaggedpost_starredcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentUpvotes',
            new_name='CommentUpvote',
        ),
    ]
