# Generated by Django 2.0.1 on 2018-03-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('NF', 'New Follower'), ('NC', 'New Comment'), ('NR', 'New Reply'), ('NU', 'New Upvote'), ('ND', 'New Downvote'), ('NM', 'New Milestone'), ('NM', 'New Post')], max_length=100)),
                ('object_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('object_type', models.CharField(choices=[('P', 'Post'), ('U', 'User'), ('T', 'Topic'), ('C', 'Comment')], max_length=100)),
                ('text', models.TextField()),
                ('thumbnail', models.ImageField(default='/default/default_notification.png', upload_to='notifications')),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
