# Generated by Django 2.0.1 on 2018-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20180326_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automobile',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
    ]
