# Generated by Django 2.0.1 on 2018-05-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_automobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCass',
            fields=[
            ],
        ),
    ]
