# Generated by Django 2.0.1 on 2018-05-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_notificationcass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationcass',
            options={'managed': False},
        ),
    ]
