# Generated by Django 2.0.1 on 2018-05-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0002_auto_20180320_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='header',
            field=models.ImageField(default='/default/post-header.png', upload_to='topics-header-images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(default='/default/user.png', upload_to='topics'),
        ),
    ]
