# Generated by Django 2.0.1 on 2018-05-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0003_auto_20180510_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='header',
            new_name='header_image',
        ),
    ]
