# Generated by Django 2.0.1 on 2018-05-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Topic', '0004_auto_20180510_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='followers',
        ),
    ]
