# Generated by Django 2.0.1 on 2018-03-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0005_flaggedcomment_flaggedpost_starredcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Topic', '0002_auto_20180320_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('starts', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('assoc_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
                ('assoc_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Topic.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('votes', models.PositiveIntegerField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Poll.Poll')),
            ],
        ),
        migrations.CreateModel(
            name='UserPolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Poll.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
