# Generated by Django 2.0.1 on 2018-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_auto_20180321_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
