# Generated by Django 2.0.1 on 2018-03-22 21:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_poll_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolled',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolled',
            name='poll_option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Poll.PollOption'),
            preserve_default=False,
        ),
    ]
